/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project_asi_1;

/**
 *
 * @author Lucas
 */
public class eleves_supprimer extends javax.swing.JPanel {

    /**
     * Creates new form eleves_supprimer
     */
    public eleves_supprimer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelEleve_supprimer = new javax.swing.JLabel();
        jButtonEleve_oui_supprimer = new javax.swing.JButton();
        jButtonEleve_non_supprimer = new javax.swing.JButton();

        jLabelEleve_supprimer.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabelEleve_supprimer.setText("Voulez vous supprimer _____ des élèves ?");

        jButtonEleve_oui_supprimer.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButtonEleve_oui_supprimer.setText("Oui");

        jButtonEleve_non_supprimer.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButtonEleve_non_supprimer.setText("Non");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(jLabelEleve_supprimer)
                .addContainerGap(93, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(228, 228, 228)
                .addComponent(jButtonEleve_oui_supprimer, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonEleve_non_supprimer, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(264, 264, 264))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(204, 204, 204)
                .addComponent(jLabelEleve_supprimer)
                .addGap(141, 141, 141)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonEleve_oui_supprimer, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEleve_non_supprimer, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(240, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEleve_non_supprimer;
    private javax.swing.JButton jButtonEleve_oui_supprimer;
    private javax.swing.JLabel jLabelEleve_supprimer;
    // End of variables declaration//GEN-END:variables
}
