/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project_asi_1;

/**
 *
 * @author Lucas
 */
public class groupes_supp_bd extends javax.swing.JPanel {

    /**
     * Creates new form groupes_supp_bd
     */
    public groupes_supp_bd() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonGroupe_oui_supprimerBD = new javax.swing.JButton();
        jButtonGroupe_non_supprimerBD = new javax.swing.JButton();
        jLabelGroupe_supprimer_bd = new javax.swing.JLabel();

        jButtonGroupe_oui_supprimerBD.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButtonGroupe_oui_supprimerBD.setText("Oui");

        jButtonGroupe_non_supprimerBD.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButtonGroupe_non_supprimerBD.setText("Non");

        jLabelGroupe_supprimer_bd.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabelGroupe_supprimer_bd.setText("<html><p>Voulez vous supprimer la  <br>base  _____ du groupe _____ ?</p></html>");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(228, 228, 228)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelGroupe_supprimer_bd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonGroupe_oui_supprimerBD, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 278, Short.MAX_VALUE)
                        .addComponent(jButtonGroupe_non_supprimerBD, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(264, 264, 264))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addComponent(jLabelGroupe_supprimer_bd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(219, 219, 219)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonGroupe_oui_supprimerBD, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonGroupe_non_supprimerBD, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(182, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonGroupe_non_supprimerBD;
    private javax.swing.JButton jButtonGroupe_oui_supprimerBD;
    private javax.swing.JLabel jLabelGroupe_supprimer_bd;
    // End of variables declaration//GEN-END:variables
}
