/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project_asi_1;

/**
 *
 * @author Elodie
 */
public class BD extends javax.swing.JPanel {

    /**
     * Creates new form BD
     */
    public BD() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblBD_BD = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnBD_retour = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listBD_eleve = new javax.swing.JList<>();
        txtBD_search = new javax.swing.JTextField();
        btnBD_loupe = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        listBD_bd = new javax.swing.JList<>();
        btnBD_creer = new javax.swing.JButton();
        btnBD_supprimer = new javax.swing.JButton();
        btnBD_modifier = new javax.swing.JButton();

        lblBD_BD.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        lblBD_BD.setText("Base de données");

        btnBD_retour.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btnBD_retour.setText("Retour");
        btnBD_retour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBD_retourActionPerformed(evt);
            }
        });

        listBD_eleve.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        listBD_eleve.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Eleve1", "Eleve2", "Eleve3", "Eleve4", "Eleve5", "Eleve6" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listBD_eleve);

        txtBD_search.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        txtBD_search.setForeground(new java.awt.Color(204, 204, 204));
        txtBD_search.setText("Rechercher...");
        txtBD_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBD_searchActionPerformed(evt);
            }
        });

        btnBD_loupe.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btnBD_loupe.setText("<html>&#128269;</html>");

        listBD_bd.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        listBD_bd.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "BD1", "BD2", "BD3", "BD4" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(listBD_bd);

        btnBD_creer.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btnBD_creer.setText("Créer");

        btnBD_supprimer.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btnBD_supprimer.setText("Supprimer");
        btnBD_supprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBD_supprimerActionPerformed(evt);
            }
        });

        btnBD_modifier.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btnBD_modifier.setText("Modifier");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(375, Short.MAX_VALUE)
                .addComponent(lblBD_BD)
                .addGap(346, 346, 346))
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtBD_search, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBD_loupe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 527, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnBD_retour)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnBD_creer, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btnBD_modifier, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnBD_supprimer))))
                .addGap(28, 28, 28))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel2)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblBD_BD)
                .addGap(84, 84, 84)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtBD_search, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBD_loupe)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnBD_creer)
                            .addComponent(btnBD_modifier)
                            .addComponent(btnBD_supprimer))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 159, Short.MAX_VALUE)
                        .addComponent(btnBD_retour)
                        .addContainerGap())))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel2)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBD_retourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBD_retourActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBD_retourActionPerformed

    private void txtBD_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBD_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBD_searchActionPerformed

    private void btnBD_supprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBD_supprimerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBD_supprimerActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBD_creer;
    private javax.swing.JButton btnBD_loupe;
    private javax.swing.JButton btnBD_modifier;
    private javax.swing.JButton btnBD_retour;
    private javax.swing.JButton btnBD_supprimer;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblBD_BD;
    private javax.swing.JList<String> listBD_bd;
    private javax.swing.JList<String> listBD_eleve;
    private javax.swing.JTextField txtBD_search;
    // End of variables declaration//GEN-END:variables
}
