/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project_asi_1.Views;

import java.awt.Frame;

/**
 *
 * @author Lucas
 */
public class eleves_modifier extends javax.swing.JPanel {

    /**
     * Creates new form eleves_modifier
     */
    public eleves_modifier() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblEleve_mail_modifier = new javax.swing.JLabel();
        jTextFieldEleve_nom_modifier = new javax.swing.JTextField();
        jTextFieldEleve_mail_modifier = new javax.swing.JTextField();
        jTextFieldEleve_prenom_modifier = new javax.swing.JTextField();
        lblEleve_prenom_modifier = new javax.swing.JLabel();
        lblEleve_modifier = new javax.swing.JLabel();
        lblEleve_nom_modifier = new javax.swing.JLabel();
        btnEleve_retour_modifier = new javax.swing.JButton();
        btnEleve_valider_modifier = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1080, 720));

        lblEleve_mail_modifier.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblEleve_mail_modifier.setText("Mail");

        jTextFieldEleve_nom_modifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEleve_nom_modifierActionPerformed(evt);
            }
        });

        jTextFieldEleve_mail_modifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEleve_mail_modifierActionPerformed(evt);
            }
        });

        jTextFieldEleve_prenom_modifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEleve_prenom_modifierActionPerformed(evt);
            }
        });

        lblEleve_prenom_modifier.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblEleve_prenom_modifier.setText("Prénom");

        lblEleve_modifier.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        lblEleve_modifier.setText("Modifier");

        lblEleve_nom_modifier.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblEleve_nom_modifier.setText("Nom");

        btnEleve_retour_modifier.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnEleve_retour_modifier.setText("Retour");
        btnEleve_retour_modifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEleve_retour_modifierActionPerformed(evt);
            }
        });

        btnEleve_valider_modifier.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnEleve_valider_modifier.setText("Valider");
        btnEleve_valider_modifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEleve_valider_modifierActionPerformed(evt);
            }
        });

        btnExit.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnExit.setText("X");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(446, 446, 446)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnEleve_valider_modifier, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEleve_modifier)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(btnEleve_retour_modifier, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(300, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblEleve_nom_modifier)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextFieldEleve_nom_modifier, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblEleve_mail_modifier)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextFieldEleve_mail_modifier, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblEleve_prenom_modifier)
                                .addGap(107, 107, 107)
                                .addComponent(jTextFieldEleve_prenom_modifier, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(327, 327, 327))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldEleve_nom_modifier, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblEleve_modifier)
                        .addGap(97, 97, 97)
                        .addComponent(lblEleve_nom_modifier)))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEleve_prenom_modifier)
                    .addComponent(jTextFieldEleve_prenom_modifier, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEleve_mail_modifier)
                    .addComponent(jTextFieldEleve_mail_modifier, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(btnEleve_valider_modifier, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addComponent(btnEleve_retour_modifier, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(68, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldEleve_nom_modifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEleve_nom_modifierActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEleve_nom_modifierActionPerformed

    private void jTextFieldEleve_mail_modifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEleve_mail_modifierActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEleve_mail_modifierActionPerformed

    private void jTextFieldEleve_prenom_modifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEleve_prenom_modifierActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEleve_prenom_modifierActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnEleve_retour_modifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEleve_retour_modifierActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        Frame.getFrames()[0].remove(this);
        Frame.getFrames()[0].add(new project_asi_1.Views.eleves());
        Frame.getFrames()[0].setVisible(true);
    }//GEN-LAST:event_btnEleve_retour_modifierActionPerformed

    private void btnEleve_valider_modifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEleve_valider_modifierActionPerformed
        // TODO add your handling code here:
        Frame.getFrames()[0].remove(this);
        Frame.getFrames()[0].add(new project_asi_1.Views.eleves());
        Frame.getFrames()[0].setVisible(true);
    }//GEN-LAST:event_btnEleve_valider_modifierActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEleve_retour_modifier;
    private javax.swing.JButton btnEleve_valider_modifier;
    private javax.swing.JButton btnExit;
    private javax.swing.JTextField jTextFieldEleve_mail_modifier;
    private javax.swing.JTextField jTextFieldEleve_nom_modifier;
    private javax.swing.JTextField jTextFieldEleve_prenom_modifier;
    private javax.swing.JLabel lblEleve_mail_modifier;
    private javax.swing.JLabel lblEleve_modifier;
    private javax.swing.JLabel lblEleve_nom_modifier;
    private javax.swing.JLabel lblEleve_prenom_modifier;
    // End of variables declaration//GEN-END:variables
}
