/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project_asi_1.Views;

import java.awt.Frame;
import project_asi_1.Classes.DAO.GroupeDAO;
import project_asi_1.Classes.Groupe;

/**
 *
 * @author Lucas
 */
public class groupes_creer extends javax.swing.JPanel {

    public groupes_creer() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelGroupe_creer = new javax.swing.JLabel();
        jTextFieldGroupe_creer_nom = new javax.swing.JTextField();
        lblEGroupe_creer_nom = new javax.swing.JLabel();
        jButtonGroupe_creer_annuler = new javax.swing.JButton();
        jButtonGroupe_creer_valider = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();

        jLabelGroupe_creer.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabelGroupe_creer.setText("Créer");

        jTextFieldGroupe_creer_nom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldGroupe_creer_nomActionPerformed(evt);
            }
        });

        lblEGroupe_creer_nom.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblEGroupe_creer_nom.setText("Nom :");

        jButtonGroupe_creer_annuler.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButtonGroupe_creer_annuler.setText("Annuler");
        jButtonGroupe_creer_annuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGroupe_creer_annulerActionPerformed(evt);
            }
        });

        jButtonGroupe_creer_valider.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButtonGroupe_creer_valider.setText("Valider");
        jButtonGroupe_creer_valider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGroupe_creer_validerActionPerformed(evt);
            }
        });

        btnExit.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnExit.setText("X");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jButtonGroupe_creer_annuler, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonGroupe_creer_valider, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(362, 362, 362)
                        .addComponent(lblEGroupe_creer_nom)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldGroupe_creer_nom, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(506, 506, 506)
                        .addComponent(jLabelGroupe_creer)))
                .addGap(457, 602, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 143, Short.MAX_VALUE)
                .addComponent(jLabelGroupe_creer)
                .addGap(102, 102, 102)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldGroupe_creer_nom, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEGroupe_creer_nom))
                .addGap(187, 187, 187)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonGroupe_creer_annuler, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonGroupe_creer_valider, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldGroupe_creer_nomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldGroupe_creer_nomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldGroupe_creer_nomActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void jButtonGroupe_creer_annulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGroupe_creer_annulerActionPerformed
        // TODO add your handling code here:
        Frame.getFrames()[0].remove(this);
        Frame.getFrames()[0].add(new project_asi_1.Views.groupes());
        Frame.getFrames()[0].setVisible(true);
    }//GEN-LAST:event_jButtonGroupe_creer_annulerActionPerformed

    private void jButtonGroupe_creer_validerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGroupe_creer_validerActionPerformed
        try {

            Groupe g = new Groupe(jTextFieldGroupe_creer_nom.getText());
            GroupeDAO groupeDao = new GroupeDAO();

            groupeDao.saveGroupe(g);
            Frame.getFrames()[0].remove(this);
            Frame.getFrames()[0].add(new project_asi_1.Views.groupes());
            Frame.getFrames()[0].setVisible(true);

        } catch (Exception e) {
            System.out.println(e);
        }

    }//GEN-LAST:event_jButtonGroupe_creer_validerActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton jButtonGroupe_creer_annuler;
    private javax.swing.JButton jButtonGroupe_creer_valider;
    private javax.swing.JLabel jLabelGroupe_creer;
    private javax.swing.JTextField jTextFieldGroupe_creer_nom;
    private javax.swing.JLabel lblEGroupe_creer_nom;
    // End of variables declaration//GEN-END:variables
}
