/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project_asi_1;

/**
 *
 * @author Lucas
 */
public class groupes_addBD extends javax.swing.JPanel {

    /**
     * Creates new form groupes_addBD
     */
    public groupes_addBD() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelGroupe_addBD = new javax.swing.JLabel();
        jComboBox1Groupe_addBD = new javax.swing.JComboBox<>();
        jButtonGroupe_addBD_annuler = new javax.swing.JButton();
        jButtonGroupe_addBD_valider = new javax.swing.JButton();

        jLabelGroupe_addBD.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabelGroupe_addBD.setText("Ajouter une base de donnée");

        jComboBox1Groupe_addBD.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1Groupe_addBD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1Groupe_addBDActionPerformed(evt);
            }
        });

        jButtonGroupe_addBD_annuler.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButtonGroupe_addBD_annuler.setText("Annuler");

        jButtonGroupe_addBD_valider.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButtonGroupe_addBD_valider.setText("Valider");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(jButtonGroupe_addBD_annuler, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonGroupe_addBD_valider, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(244, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelGroupe_addBD)
                    .addComponent(jComboBox1Groupe_addBD, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(236, 236, 236))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(jLabelGroupe_addBD)
                .addGap(32, 32, 32)
                .addComponent(jComboBox1Groupe_addBD, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 285, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonGroupe_addBD_valider, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonGroupe_addBD_annuler, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(101, 101, 101))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1Groupe_addBDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1Groupe_addBDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1Groupe_addBDActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonGroupe_addBD_annuler;
    private javax.swing.JButton jButtonGroupe_addBD_valider;
    private javax.swing.JComboBox<String> jComboBox1Groupe_addBD;
    private javax.swing.JLabel jLabelGroupe_addBD;
    // End of variables declaration//GEN-END:variables
}
