/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project_asi_1.Views;

import java.awt.Frame;

/**
 *
 * @author Lucas
 */
public class groupes_modifier extends javax.swing.JPanel {

    /**
     * Creates new form groupes_modifier
     */
    public groupes_modifier() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldGroupe_modifier_nom = new javax.swing.JTextField();
        lblEGroupe_modifier_nom = new javax.swing.JLabel();
        jLabelGroupe_modifier = new javax.swing.JLabel();
        jButtonGroupe_modifier_annuler = new javax.swing.JButton();
        jButtonGroupe_modifier_valider = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();

        jTextFieldGroupe_modifier_nom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldGroupe_modifier_nomActionPerformed(evt);
            }
        });

        lblEGroupe_modifier_nom.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblEGroupe_modifier_nom.setText("Nom :");

        jLabelGroupe_modifier.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabelGroupe_modifier.setText("Modifier");

        jButtonGroupe_modifier_annuler.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButtonGroupe_modifier_annuler.setText("Annuler");
        jButtonGroupe_modifier_annuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGroupe_modifier_annulerActionPerformed(evt);
            }
        });

        jButtonGroupe_modifier_valider.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButtonGroupe_modifier_valider.setText("Valider");
        jButtonGroupe_modifier_valider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGroupe_modifier_validerActionPerformed(evt);
            }
        });

        btnExit.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnExit.setText("X");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButtonGroupe_modifier_annuler, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonGroupe_modifier_valider, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(94, 94, 94))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(415, 415, 415)
                                .addComponent(jLabelGroupe_modifier))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(292, 292, 292)
                                .addComponent(lblEGroupe_modifier_nom)
                                .addGap(75, 75, 75)
                                .addComponent(jTextFieldGroupe_modifier_nom, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(297, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jLabelGroupe_modifier)
                .addGap(103, 103, 103)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldGroupe_modifier_nom, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEGroupe_modifier_nom))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 276, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonGroupe_modifier_valider, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonGroupe_modifier_annuler, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(79, 79, 79))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldGroupe_modifier_nomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldGroupe_modifier_nomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldGroupe_modifier_nomActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnExitActionPerformed

    private void jButtonGroupe_modifier_annulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGroupe_modifier_annulerActionPerformed
        // TODO add your handling code here:
        Frame.getFrames()[0].remove(this);
        Frame.getFrames()[0].add(new project_asi_1.Views.groupes());
        Frame.getFrames()[0].setVisible(true);
    }//GEN-LAST:event_jButtonGroupe_modifier_annulerActionPerformed

    private void jButtonGroupe_modifier_validerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGroupe_modifier_validerActionPerformed
        // TODO add your handling code here:
        Frame.getFrames()[0].remove(this);
        Frame.getFrames()[0].add(new project_asi_1.Views.groupes());
        Frame.getFrames()[0].setVisible(true);
    }//GEN-LAST:event_jButtonGroupe_modifier_validerActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton jButtonGroupe_modifier_annuler;
    private javax.swing.JButton jButtonGroupe_modifier_valider;
    private javax.swing.JLabel jLabelGroupe_modifier;
    private javax.swing.JTextField jTextFieldGroupe_modifier_nom;
    private javax.swing.JLabel lblEGroupe_modifier_nom;
    // End of variables declaration//GEN-END:variables
}
