/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project_asi_1.Views;

import java.awt.Frame;
import java.io.IOException;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import project_asi_1.Classes.DAO.EleveDAO;
import project_asi_1.Classes.Eleve;
import project_asi_1.Classes.Groupe;
import project_asi_1.Classes.utils.BddUtils;
import project_asi_1.Classes.utils.RepoUtils;

/**
 *
 * @author Lucas
 */
public class groupes_addmembre extends javax.swing.JPanel {

    public static Groupe g2;

    public groupes_addmembre(Groupe g) {
        g2 = g;
        initComponents();
        remplirListEleve(g2);
    }

    public void remplirListEleve(Groupe g) {
        EleveDAO eleveDao = new EleveDAO();
        List<Eleve> eleves = eleveDao.getEleves();
        for (Eleve eleve : eleves) {
            if (!g.getEleves().contains(eleve)) {
                jComboBox1.addItem(eleve);
            }

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelGroupe_addMembre = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButtonGroupe_addMembre_annuler = new javax.swing.JButton();
        jButtonGroupe_addMembre_valider = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();

        jLabelGroupe_addMembre.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabelGroupe_addMembre.setText("Ajouter un membre");

        jButtonGroupe_addMembre_annuler.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButtonGroupe_addMembre_annuler.setText("Annuler");
        jButtonGroupe_addMembre_annuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGroupe_addMembre_annulerActionPerformed(evt);
            }
        });

        jButtonGroupe_addMembre_valider.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButtonGroupe_addMembre_valider.setText("Valider");
        jButtonGroupe_addMembre_valider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGroupe_addMembre_validerActionPerformed(evt);
            }
        });

        btnExit.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnExit.setText("X");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(jButtonGroupe_addMembre_annuler, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonGroupe_addMembre_valider, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(333, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelGroupe_addMembre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(334, 334, 334))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(jLabelGroupe_addMembre)
                .addGap(94, 94, 94)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 249, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonGroupe_addMembre_valider, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonGroupe_addMembre_annuler, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(101, 101, 101))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void jButtonGroupe_addMembre_annulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGroupe_addMembre_annulerActionPerformed
        // TODO add your handling code here:
        Frame.getFrames()[0].remove(this);
        Frame.getFrames()[0].add(new project_asi_1.Views.groupes());
        Frame.getFrames()[0].setVisible(true);
    }//GEN-LAST:event_jButtonGroupe_addMembre_annulerActionPerformed

    private void jButtonGroupe_addMembre_validerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGroupe_addMembre_validerActionPerformed
        try {
            Eleve e = (Eleve) jComboBox1.getSelectedItem();
            e.addGroupes(g2);
            EleveDAO eleveDao = new EleveDAO();
            eleveDao.refresh(e);

            g2.getRepo().forEach((repository) -> {
                try {
                    RepoUtils.addEleveOnRepo(e, repository);
                } catch (IOException ex) {
                    Logger.getLogger(groupes_addmembre.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(groupes_addmembre.class.getName()).log(Level.SEVERE, null, ex);
                }
                System.out.println(repository);
            });
            try {
                g2.getBdd().forEach((bdd) -> {
                    BddUtils.addEleveOnSchema(e, bdd);
                    System.out.println(bdd);
                });

            } catch (Exception ef) {
                System.out.println(ef);
            }

            Frame.getFrames()[0].remove(this);
            Frame.getFrames()[0].add(new project_asi_1.Views.groupes());
            Frame.getFrames()[0].setVisible(true);

        } catch (Exception e) {

            System.out.println(e);
        }

    }//GEN-LAST:event_jButtonGroupe_addMembre_validerActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton jButtonGroupe_addMembre_annuler;
    private javax.swing.JButton jButtonGroupe_addMembre_valider;
    private javax.swing.JComboBox<Eleve> jComboBox1;
    private javax.swing.JLabel jLabelGroupe_addMembre;
    // End of variables declaration//GEN-END:variables
}
